// src/App.tsx
import { useEffect, useState } from "react";
import { ChevronDown, Check, Plus, Pencil, Trash2 } from "lucide-react";
import { Toaster } from "@/components/ui/sonner";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Input } from "@/components/ui/input";
import AppSidebar from "@/components/AppSidebar";
import GlobalDialogHost from "@/components/GlobalDialogHost";
import TitleBarControls from "@/components/TitleBarControls";
import { AnimatedGridPattern } from "@/components/ui/animated-grid-pattern";
import { Particles } from "@/components/ui/particles";
import Onboarding from "@/views/Onboarding";
import { AppRoutes } from "@/routers";
import { t } from "@/i18n";
import { useAppStore } from "@/stores/app";
import { usePrefStore } from "@/stores/pref";
import { useProfilesStore } from "@/stores/profiles";
import { dialog, message } from "@/utils/ui/feedback";
import { checkRunningInstance } from "@/services/launcher";
import { importFromFile, importFromUrl } from "@/services/brp";
import { getCurrentWebview } from "@tauri-apps/api/webview";
import {
  getCurrent as getCurrentDeepLink,
  onOpenUrl
} from "@tauri-apps/plugin-deep-link";
import { useNavigate, useLocation } from "react-router-dom";
import { getVersion } from "@tauri-apps/api/app";

/** Compute dark-mode state from pref.theme + system preference. */
function useDarkMode(): boolean {
  const theme = usePrefStore(s => s.theme);
  const [systemDark, setSystemDark] = useState(
    () =>
      typeof window !== "undefined" &&
      window.matchMedia("(prefers-color-scheme: dark)").matches
  );

  useEffect(() => {
    const mq = window.matchMedia("(prefers-color-scheme: dark)");
    const handler = (e: MediaQueryListEvent) => setSystemDark(e.matches);
    mq.addEventListener("change", handler);
    return () => mq.removeEventListener("change", handler);
  }, []);

  return theme === "dark" || (theme === "auto" && systemDark);
}

const promptName = (
  title: string,
  initial: string,
  onOk: (v: string) => void
) => {
  let value = initial;
  dialog.create({
    title,
    content: () => (
      <Input
        defaultValue={initial}
        placeholder={t("profile.namePlaceholder")}
        onChange={e => (value = e.target.value)}
      />
    ),
    positiveText: t("common.dialog.confirm"),
    negativeText: t("common.dialog.cancel"),
    onPositiveClick: () => {
      const name = value.trim();
      if (name) onOk(name);
    }
  });
};

export default function App() {
  const isDark = useDarkMode();

  // Apply .dark class on <html>.
  useEffect(() => {
    document.documentElement.classList.toggle("dark", isDark);
  }, [isDark]);

  const hasInstance = useAppStore(s => !!s.selectedInstanceData);

  return (
    <>
      <Toaster richColors closeButton position="top-right" />
      <GlobalDialogHost />
      <TooltipProvider>
        {hasInstance ? <MainLayout /> : <Onboarding />}
      </TooltipProvider>
    </>
  );
}

function MainLayout() {
  const navigate = useNavigate();
  const location = useLocation();
  const [collapsed, setCollapsed] = useState(false);
  const [appVersion, setAppVersion] = useState("");
  const backgroundType = usePrefStore(s => s.backgroundType);
  const isDark = useDarkMode();

  useEffect(() => {
    getVersion().then(setAppVersion);
  }, []);

  // Profile store data
  const profiles = useProfilesStore(s => s.index.profiles);
  const currentProfile = useProfilesStore(s => {
    const idx = s.index;
    return idx.profiles.find(p => p.id === idx.currentId);
  });

  // Restore last route once on mount (initStores has loaded instance already).
  const route = usePrefStore(s => s.route);
  useEffect(() => {
    const target = route || "/game";
    if (target !== location.pathname) navigate(target, { replace: true });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Persist current route on navigation.
  useEffect(() => {
    usePrefStore.setState({ route: location.pathname });
  }, [location.pathname]);

  // Poll running-instance status every second.
  const updateRunningTime = useAppStore(s => s.updateInstanceRunningTime);
  useEffect(() => {
    const id = setInterval(() => {
      checkRunningInstance();
      if (useAppStore.getState().runningInstancePid) updateRunningTime();
    }, 1000);
    return () => clearInterval(id);
  }, [updateRunningTime]);

  // BRP drag-drop + rockoon:// deep-links.
  useEffect(() => {
    let unlistenDragDrop: (() => void) | undefined;
    let unlistenDeepLink: (() => void) | undefined;

    const handleUrl = (raw: string) => {
      try {
        const parsed = new URL(raw);
        if (parsed.protocol !== "rockoon:") return;
        if (parsed.host === "import") {
          const brpUrl = parsed.searchParams.get("url");
          if (brpUrl) importFromUrl(brpUrl);
          else message.warning(t("brp.error.invalidFile"));
        }
      } catch {
        // ignore malformed URLs
      }
    };

    (async () => {
      unlistenDragDrop = await getCurrentWebview().onDragDropEvent(event => {
        if (event.payload.type === "drop") {
          const brpFiles = event.payload.paths.filter(
            p =>
              p.toLowerCase().endsWith(".brp") ||
              p.toLowerCase().endsWith(".zip")
          );
          brpFiles.forEach(p => importFromFile(p));
        }
      });

      unlistenDeepLink = await onOpenUrl(urls => urls.forEach(handleUrl));
      const startup = await getCurrentDeepLink();
      if (startup) startup.forEach(handleUrl);
    })();

    return () => {
      unlistenDragDrop?.();
      unlistenDeepLink?.();
    };
  }, []);

  const onSwitchProfile = async (id: string) => {
    if (id === currentProfile?.id) return;
    const loading = message.loading(t("profile.switching"));
    try {
      await useProfilesStore.getState().switchProfile(id);
      message.success(t("profile.switched"));
    } catch {
      message.error(t("profile.switchFailed"));
    } finally {
      loading.destroy();
    }
  };

  const onCreateProfile = () =>
    promptName(t("profile.create"), t("profile.defaultName"), async name => {
      await useProfilesStore.getState().createProfile(name);
      message.success(t("profile.created"));
    });

  const onRenameProfile = () => {
    if (!currentProfile) return;
    promptName(t("profile.rename"), currentProfile.name, async name => {
      await useProfilesStore.getState().renameProfile(currentProfile.id, name);
      message.success(t("profile.renamed"));
    });
  };

  const onDeleteProfile = () => {
    if (!currentProfile) return;
    dialog.warning({
      title: t("common.message.warning"),
      content: t("profile.deleteConfirm", { name: currentProfile.name }),
      positiveText: t("common.dialog.confirm"),
      negativeText: t("common.dialog.cancel"),
      onPositiveClick: async () => {
        await useProfilesStore.getState().deleteProfile(currentProfile.id);
        message.success(t("profile.deleted"));
      }
    });
  };

  const currentProfileName = currentProfile?.name ?? t("common.none");
  const deleteDisabled = profiles.length <= 1;

  // Persist route on every render cycle (cheap; only saves pref).
  // Better: subscribe to location changes.
  useEffect(() => {
    const handler = () => {
      const path = window.location.pathname;
      if (path && path !== "/") {
        usePrefStore.setState({ route: path });
      }
    };
    window.addEventListener("popstate", handler);
    return () => window.removeEventListener("popstate", handler);
  }, []);

  return (
    <div className="flex h-screen flex-col bg-background text-foreground">
      <header className="flex h-13 shrink-0 items-center gap-4 border-b bg-background pl-4 pr-0">
        <div className="flex items-center gap-2">
          <img
            src="/logo.png"
            alt="Rockoon"
            className="size-5 rounded-sm"
            draggable={false}
          />
          <span className="select-none text-base font-semibold tracking-tight">
            Rockoon
          </span>
          {appVersion && (
            <span className="select-none text-xs text-muted-foreground">
              v{appVersion}
            </span>
          )}
        </div>
        <div
          data-tauri-drag-region
          className="flex-1 self-stretch"
          aria-hidden="true"
        />
        <div className="flex items-center gap-2">
          <span className="hidden text-sm text-muted-foreground sm:inline">
            {t("profile.currentLabel")}
          </span>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" size="sm">
                {currentProfileName}
                <ChevronDown className="ml-1 size-4 opacity-70" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="min-w-[180px]">
              <DropdownMenuLabel>{t("profile.currentLabel")}</DropdownMenuLabel>
              <DropdownMenuSeparator />
              {profiles.map(p => (
                <DropdownMenuItem
                  key={p.id}
                  onClick={() => onSwitchProfile(p.id)}
                >
                  {p.id === currentProfile?.id ? (
                    <Check className="size-4" />
                  ) : (
                    <span className="size-4" />
                  )}
                  {p.name}
                </DropdownMenuItem>
              ))}
              <DropdownMenuSeparator />
              <DropdownMenuItem onClick={onCreateProfile}>
                <Plus className="size-4" />
                {t("profile.create")}
              </DropdownMenuItem>
              <DropdownMenuItem onClick={onRenameProfile}>
                <Pencil className="size-4" />
                {t("profile.rename")}
              </DropdownMenuItem>
              <DropdownMenuItem
                disabled={deleteDisabled}
                onClick={onDeleteProfile}
              >
                <Trash2 className="size-4" />
                {t("profile.delete")}
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>

          <TitleBarControls />
        </div>
      </header>

      <div className="relative flex flex-1 overflow-hidden">
        {/* Global background — lives outside <main> and router so route
            changes neither remount it nor let route content height push
            the layout. Sidebar/main sit on top via their own bg-background. */}
        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-0 overflow-hidden"
        >
          {backgroundType === "particles" ? (
            <Particles
              className="absolute inset-0"
              quantity={120}
              color={isDark ? "#ffffff" : "#000000"}
              ease={80}
              refresh={false}
            />
          ) : (
            <AnimatedGridPattern
              numSquares={40}
              maxOpacity={0.08}
              duration={3}
              repeatDelay={1}
              className="absolute inset-y-[-30%] h-[160%] w-full skew-y-12 [mask-image:radial-gradient(500px_circle_at_center,white,transparent)]"
            />
          )}
        </div>
        <AppSidebar collapsed={collapsed} onCollapsedChange={setCollapsed} />
        <main className="relative flex-1 overflow-auto">
          <AppRoutes />
        </main>
      </div>
    </div>
  );
}

// src/App.vue
<script lang="ts" setup>
import {
  darkTheme,
  dateEnUS,
  dateZhCN,
  enUS,
  lightTheme,
  NAvatar,
  NButton,
  NConfigProvider,
  NDropdown,
  NFlex,
  NInput,
  NLayout,
  NLayoutSider,
  NMenu,
  NScrollbar,
  NText,
  zhCN
} from "naive-ui";
import { computed, h, onMounted, onUnmounted, ref } from "vue";
import { useRouter } from "vue-router";
import { getCurrentWebview } from "@tauri-apps/api/webview";
import {
  getCurrent as getCurrentDeepLink,
  onOpenUrl
} from "@tauri-apps/plugin-deep-link";
import BasicIcon from "./views/components/MgcIcon.vue";
import { t } from "./i18n";
import { getMenuOptions } from "./routers/menu";
import { useAppStore } from "./stores/app";
import { usePrefStore } from "./stores/pref";
import { useProfilesStore } from "./stores/profiles";
import { dialog, message } from "./utils/ui/feedback";
import { useLauncherService } from "./services/launcher";
import { useBrpService } from "./services/brp";
import Onboarding from "./views/Onboarding.vue";

const app = useAppStore();
const pref = usePrefStore();
const profiles = useProfilesStore();
const router = useRouter();
const { checkRunningInstance, killInstance, launchInstance } =
  useLauncherService();
const { importFromFile, importFromUrl } = useBrpService();

const theme = computed(() => (pref.darkMode ? darkTheme : lightTheme));
const locale = computed(() => (pref.language === "zh" ? zhCN : enUS));
const dateLocale = computed(() =>
  pref.language === "zh" ? dateZhCN : dateEnUS
);

// menu related props
const menuRef = ref<InstanceType<typeof NMenu>>();
const collapsed = ref(false);
const selectedKey = ref("");
const checkInterval = ref<ReturnType<typeof setInterval>>();

// unlisten handles for global BRP listeners (drag-drop + deep-link)
let unlistenDragDrop: (() => void) | undefined;
let unlistenDeepLink: (() => void) | undefined;

/**
 * Parse and handle a rockoon:// deep-link URL.
 * Supported action: `rockoon://import?url=<encoded-brp-url>`
 */
const handleDeepLinkUrl = (raw: string) => {
  try {
    const parsed = new URL(raw);
    if (parsed.protocol !== "rockoon:") return;
    if (parsed.host === "import") {
      const brpUrl = parsed.searchParams.get("url");
      if (brpUrl) {
        importFromUrl(brpUrl);
      } else {
        message.warning(t("brp.error.invalidFile"));
      }
    }
  } catch {
    // ignore malformed URLs
  }
};

const handleDeepLinkUrls = (urls: string[]) => {
  urls.forEach(handleDeepLinkUrl);
};

const onLaunchGame = async () => {
  if (!app.selectedInstanceData) return;

  if (app.runningInstancePid) {
    const isRunning = await checkRunningInstance();
    if (isRunning) {
      message.warning(t("home.alreadyRunning"));
      return;
    }
  }

  await launchInstance();
  message.success(t("home.launching"));
};

// profile dropdown
const profileOptions = computed(() => [
  ...profiles.profiles.map(p => ({
    label: p.name,
    key: `switch:${p.id}`,
    icon:
      p.id === profiles.currentProfile?.id
        ? () => h(BasicIcon, { icon: "check-line" })
        : undefined
  })),
  { type: "divider", key: "d" },
  {
    label: t("profile.create"),
    key: "create",
    icon: () => h(BasicIcon, { icon: "add-line" })
  },
  {
    label: t("profile.rename"),
    key: "rename",
    icon: () => h(BasicIcon, { icon: "edit-line" })
  },
  {
    label: t("profile.delete"),
    key: "delete",
    disabled: profiles.profiles.length <= 1,
    icon: () => h(BasicIcon, { icon: "delete-2-line" })
  }
]);

const promptName = (title: string, initial: string, onOk: (v: string) => void) => {
  const inputValue = ref(initial);
  dialog.create({
    title,
    content: () =>
      h(NInput, {
        value: inputValue.value,
        placeholder: t("profile.namePlaceholder"),
        onUpdateValue: (v: string) => {
          inputValue.value = v;
        }
      }),
    positiveText: t("common.dialog.confirm"),
    negativeText: t("common.dialog.cancel"),
    onPositiveClick: () => {
      const name = inputValue.value.trim();
      if (name) onOk(name);
    }
  });
};

const onProfileSelect = async (key: string) => {
  if (key.startsWith("switch:")) {
    const id = key.slice("switch:".length);
    if (id === profiles.currentProfile?.id) return;
    const loading = message.loading(t("profile.switching"));
    try {
      await profiles.switchProfile(id);
      message.success(t("profile.switched"));
    } catch {
      message.error(t("profile.switchFailed"));
    } finally {
      loading.destroy();
    }
  } else if (key === "create") {
    promptName(t("profile.create"), t("profile.defaultName"), async name => {
      await profiles.createProfile(name);
      message.success(t("profile.created"));
    });
  } else if (key === "rename") {
    const cur = profiles.currentProfile;
    if (!cur) return;
    promptName(t("profile.rename"), cur.name, async name => {
      await profiles.renameProfile(cur.id, name);
      message.success(t("profile.renamed"));
    });
  } else if (key === "delete") {
    const cur = profiles.currentProfile;
    if (!cur) return;
    dialog.warning({
      title: t("common.message.warning"),
      content: t("profile.deleteConfirm", { name: cur.name }),
      positiveText: t("common.dialog.confirm"),
      negativeText: t("common.dialog.cancel"),
      onPositiveClick: async () => {
        await profiles.deleteProfile(cur.id);
        message.success(t("profile.deleted"));
      }
    });
  }
};

onMounted(async () => {
  // react to route change
  router.afterEach(() => {
    const currentPath = router.currentRoute.value.path;

    // update selected key
    selectedKey.value = currentPath;

    // remember latest route
    pref.route = currentPath;

    // auto-expand selected submenu
    menuRef.value?.showOption(currentPath);
  });

  // show welcome message
  if (pref.showWelcome) {
    setTimeout(() => {
      message.info(t("message.welcome"));
    }, 50);
  }

  // 定期检查游戏进程状态并保存游玩时间（每1秒检查一次）
  checkInterval.value = setInterval(() => {
    checkRunningInstance();
    // 更新当前的游玩时间（即使游戏还在运行）
    if (app.runningInstancePid) {
      app.updateInstanceRunningTime();
    }
  }, 1000);

  // BRP drag-drop: accept .brp / .zip anywhere in the window
  unlistenDragDrop = await getCurrentWebview().onDragDropEvent(event => {
    if (event.payload.type === "drop") {
      const brpFiles = event.payload.paths.filter(
        p => p.toLowerCase().endsWith(".brp") || p.toLowerCase().endsWith(".zip")
      );
      brpFiles.forEach(p => importFromFile(p));
    }
  });

  // rockoon:// deep-link: handle while app is running
  unlistenDeepLink = await onOpenUrl(handleDeepLinkUrls);

  // cold-start: app launched via rockoon:// — check startup URLs
  const startupUrls = await getCurrentDeepLink();
  if (startupUrls) handleDeepLinkUrls(startupUrls);
});

onUnmounted(() => {
  // 清理定时器
  if (checkInterval.value) {
    clearInterval(checkInterval.value);
  }
  // 清理 BRP 监听器
  unlistenDragDrop?.();
  unlistenDeepLink?.();
});
</script>

<template>
  <n-config-provider
    :theme
    :locale
    :date-locale="dateLocale"
    style="--main-ctn-h: calc(100vh - 52px)"
  >
    <template v-if="app.selectedInstanceData">
      <n-layout
        style="height: 52px; border-bottom: 1px solid rgb(239 239 245)"
      >
        <n-flex
          align="center"
          justify="space-between"
          style="height: 100%; padding-right: 16px; padding-left: 16px"
        >
          <n-flex style="flex: 1">
            <n-avatar>
              <BasicIcon icon="avatar-line" />
            </n-avatar>
            <n-button @click="message.info(t('message.noImpl'))">
              {{ t("header.pleaseLogin") }}
            </n-button>
          </n-flex>

          <n-flex align="center" :size="6">
            <n-text depth="3">{{ t("profile.currentLabel") }}</n-text>
            <n-dropdown
              :options="profileOptions"
              trigger="click"
              placement="bottom"
              @select="onProfileSelect"
            >
              <n-button quaternary type="primary">
                {{ profiles.currentProfile?.name ?? t("common.none") }}
                <BasicIcon icon="arrow-down-s-line" style="margin-left: 4px" />
              </n-button>
            </n-dropdown>
          </n-flex>

          <n-flex justify="flex-end" style="flex: 1">
            <n-button
              v-if="!app.runningInstancePid"
              type="primary"
              @click="onLaunchGame"
            >
              <template #icon>
                <BasicIcon icon="play-line" />
              </template>
              {{ t("home.launch") }}
            </n-button>
            <n-button v-else type="error" @click="killInstance">
              <template #icon>
                <BasicIcon icon="stop-line" />
              </template>
              {{ t("home.stop") }}
            </n-button>
          </n-flex>
        </n-flex>
      </n-layout>

      <n-layout has-sider style="width: 100vw; height: var(--main-ctn-h)">
        <n-layout-sider
          bordered
          show-trigger
          collapse-mode="width"
          :width="180"
          :collapsed-width="50"
          :collapsed="collapsed"
          @collapse="collapsed = true"
          @expand="collapsed = false"
        >
          <n-scrollbar>
            <n-menu
              ref="menuRef"
              v-model:value="selectedKey"
              :options="getMenuOptions()"
              :indent="20"
            />
          </n-scrollbar>
        </n-layout-sider>

        <n-layout
          class="main-container-scrollbar-fix"
          style="height: 100%"
          :native-scrollbar="false"
        >
          <router-view v-slot="{ Component }">
            <transition name="fade-slide" mode="out-in">
              <component :is="Component" class="view" />
            </transition>
          </router-view>
        </n-layout>
      </n-layout>
    </template>
    <Onboarding v-else />
  </n-config-provider>
</template>

<style scoped>
.fade-slide-enter-active,
.fade-slide-leave-active {
  transition: all 150ms ease;
}

.fade-slide-enter-from {
  opacity: 0;
  transform: translateY(10px);
}

.fade-slide-enter-to {
  opacity: 1;
  transform: translateY(0);
}

.fade-slide-leave-from {
  opacity: 1;
  transform: translateY(0);
}

.fade-slide-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}
</style>
